### ISSUE TITLE
question: what about computeds?

### ISSUE THREAD

**Issue by cellvia** [danielearwicker/json-mobx#1]
if there are computeds (with no setters) i want in the json so they make it into db (their values AT THAT TIME of saving) would this still work? i suppose you'd just check when re-applying the json at load if there was a setter to receive the value?

**Comment by danielearwicker** [comment]
You can achieve this by writing a custom `json` getter/setter but yes it sounds reasonable to provide a way to store "snapshots" of computer values and ignore them on deserialising so I will take a look when I have a moment.

**Comment by cellvia** [comment]
that would be awesome!! also interested to see how you'd handle checking for valid targets in deserialization in this case...  if something has a setter, but is a computed getter, should it still receive its previously saved value?  that may often result in an incorrect value.  i guess this may be a case where one size does not fit all

**Comment by danielearwicker** [comment]
A get/set pair should consistently receive back anything it persisted. If you need anything stranger than that, use a helper object with its own `json` property to customise the behaviour. I will include something along these lines in the tests.

**Comment by danielearwicker** [comment]
See 0.4.0 - has some tests including `getterWithoutSetter`, as well as a few other improvements.

**Comment by cellvia** [comment]
Awesome!
