### ISSUE TITLE
You are getting a kiss and a pint

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/json-mobx#2]
My gf is British and we might be coming to London this year.  If you are around I am buying you a pint and giving you a kiss on the forehead for this.  Truly.fucking.awesome.thankyou.

**Comment by danielearwicker** [comment]
No problem, glad it is useful to someone else!

To be honest I'm assuming this is a stopgap that could be replace with MobX-state-tree when that has got more definite. This library is way less ambitious and more simplistic, so it has hardly any code (it's little more than a pattern) but ticks the boxes for what I need most urgently.

I should definitely write SOME tests though. Also a demo of a simple vector graphics editor.

**Comment by mrjjwright** [comment]
It works like a charm.  I plan to use it to replace state-tree as well.  Which is a huge relief!  Keep the examples coming!

**Comment by mrjjwright** [comment]
Hey, should this thing be capable of serializing pretty deep graphs?  Are you using it to do so?  I am attempting to use it for that so want to make sure that it's ok.

**Comment by mrjjwright** [comment]
Can you provide an example of a custom getter and setter, I can't figure it out.

**Comment by danielearwicker** [comment]
It shouldn't have a problem with depth, it's just simple recursion. It is designed for tree structures though, not random graphs.

`Polymorph` from the source is a simple example of a class that defines its own persistence format:

```ts
    @computed get json() {
        return {
            type: this.type,
            settings: json.save(this.ref) 
        };
    }
    set json(data: any) {
        if (data && data.type) {
            this.set(data.type);
            json.load(this.ref, data.settings);
        }
    }
```

**Comment by mrjjwright** [comment]
Thanks!
