### ISSUE TITLE
Built in support for arrays?

### ISSUE THREAD

**Issue by mrjjwright** [danielearwicker/json-mobx#3]
Setting @json on an array doesn't cause the json prop of each item in the array to be called by default during a `save` unless using Collection.  Is that a drawback?  It kind of seems like it but am I missing something?   It seems that prevents this from being used with simple nested object hierarchies that use their own arrays.

**Comment by danielearwicker** [comment]
Agreed. The reason for `Collection` is to do reconciliation by item IDs. However this means you have to put an ID on each item manually, when in fact the library could do this for you (stash a secret property).

So I'm planning to remove `Collection` and build in that behaviour for arrays.

**Comment by danielearwicker** [comment]
By the way, a lot of other fixes in the next release, mostly in the area of class inheritance.

**Comment by mrjjwright** [comment]
Awesome, I am getting out some stuff for tomorrow for the editor I am working for my company and trying to get serialization to be rock solid.  Looking forward to your changes and thanks so much!

**Comment by danielearwicker** [comment]
If on a tight deadline stick with `Collection` for now. Quite a lot of details to work out. Like how to construct an item? One option is special decorator:

```ts
@json.arrayOf(MyClass) readonly myArray: MyClass[] = [];
```

Note the repetition of `MyClass‘, which has to be compatible but is not checked by TS.

Another option:

```ts
@json readonly myArray = json.arrayOf(MyClass);
```

The returned value from `arrayOf` is an ordinary array but with a secret property indicating the item constructor. This eliminates repetition and is fully type checked.

Note the use of `readonly` on anything marked with `@json` - I will advise doing this generally in the docs.

**Comment by mrjjwright** [comment]
Why should `@json` props be always marked `readonly`?

**Comment by danielearwicker** [comment]
Sorry, that wasn't at all clear! I mean on things that themselves have a json property (either a custom `json` computed or automatically generated by `@json`).

Obviously for primitives or plain objects they have to be mutable.

**Comment by danielearwicker** [comment]
See new version 0.5.3 and updated README. This is a breaking change! But migrating shouldn't be too bad. Where you have:

    @json myStuff = new Collection(() => new MyItem());

instead now say:

    @json readonly myStuff = json.arrayOf(MyItem);

And wherever you say `this.myStuff.items` you can simply say `this.myStuff` as it is directly an array.

Note that it is always an observable array, so no need to add `@observable` (but harmless if you do).

You should also remove all `id` properties from objects as they are no longer needed (unless you have some other need for them of course).

**Comment by mrjjwright** [comment]
Yay!!  Thank-you!!

**Comment by mrjjwright** [comment]
I get the following when I load an array with 3 items for the first time after serializing it out:

`Duplicate item id 0`.  I don't think i did anything special, trying to figure it out.

**Comment by danielearwicker** [comment]
That is a check on the items already in memory. So you must be loading into an array that already has items in it. What does the JSON look like?

**Comment by danielearwicker** [comment]
In 0.5.6 I've added a test that replicates this problem and fixed it by just discarding internal duplicates. This shouldn't change any behaviour in terms of serialisation. The IDs are only used in reconciliation to reuse existing objects as much as possible. If two have the same ID somehow then only one of them will be reused.

**Comment by mrjjwright** [comment]
Yay, awesome!  Thanks!

**Comment by danielearwicker** [comment]
Just a heads up that 0.6.0 has the same API but a new implementation of `json.array` where it defines a `json` property, so from the outside it's no different from any other live object. This is probably good for efficiency and structural sharing where you have lots of sub-lists. Obviously all the existing tests pass but let me know if you notice anything different.

**Comment by danielearwicker** [comment]
I'm also mulling over allowing `<id>` to be a string or a number, i.e. user defined, so it's possible to "render" into a data structure to update it, exactly as we do with the DOM in React.

**Comment by mrjjwright** [comment]
Wow, this is awesome stuff.  As soon as my project makes it past pilot in 2 weeks I am going to test it out.  Probably before.  :)

**Comment by danielearwicker** [comment]
Cool, will close this for now but please open specific issues if you hit problems.

**Comment by mrjjwright** [comment]
Thanks!!
